[tool.poetry]
name = "manic-mansion"
version = "0.1.0"
description = ""
authors = ["Daniel Grøtan Gregusson <danielgrotangregusson@gmail.com>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.12"
pygame = "^2.5.2"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
